name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 필요에 따라 Node.js 버전을 수정하세요.

      - name: Create .env file
        run: |
          echo "VITE_A=${{ secrets.VITE_A }}" >> .env
          echo "VITE_B=${{ secrets.VITE_B }}" >> .env

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 빌드 결과물이 생성되는 디렉토리로 수정하세요.
