name: write html file!

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 시크릿으로 동적인 환경변수 추가
        run: |
          echo "VITE_A=${{ secrets.VITE_A }}" >> .env
          echo "VITE_B=${{ secrets.VITE_B }}" >> .env
